/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./node_modules/flowbite/**/*.js",
    ],

    theme: {
        extend: {
            fontFamily: {
                PlusJakarta: ["PlusJakarta", "sans-serif"],
                NeueMachina: ["NeueMachina"],
            },
            colors: {
                primary: {
                    light: "#efe8fa",
                    "light-hover": "#e8ddf7",
                    "light-active": "#cfb8ef",
                    DEFAULT: "#631acb",
                    hover: "#5917b7",
                    active: "#4f15a2",
                    dark: "#4a1498",
                    "dark-hover": "#3b107a",
                    "dark-active": "#2d0c5b",
                    darker: "#230947",
                },
                secondary: {
                    light: "#fff2ec",
                    "light-hover": "#FFECE2",
                    "light-active": "#FED8C3",
                    DEFAULT: "#FD803D",
                    hover: "#E47337",
                    active: "#CA6631",
                    dark: "#BE602E",
                    "dark-hover": "#984D25",
                    "dark-active": "#723A1B",
                    darker: "#592D15",
                },
                info: {
                    light: "#EAF8FC",
                    "light-hover": "#E0F5FA",
                    "light-active": "#BEE9F5",
                    DEFAULT: "#2EB9E0",
                    hover: "#29A7CA",
                    active: "#2594B3",
                    dark: "#238BA8",
                    "dark-hover": "#1C6F86",
                    "dark-active": "#155365",
                    darker: "#10414E",
                },
                success: {
                    light: "#F1FBEB",
                    "light-hover": "#EAFAE0",
                    "light-active": "#D5F4C0",
                    DEFAULT: "#76DB33",
                    hover: "#6AC52E",
                    active: "#5EAF29",
                    dark: "#59A426",
                    "dark-hover": "#47831F",
                    "dark-active": "#356317",
                    darker: "#294D12",
                },
                warning: {
                    light: "#FFFEEA",
                    "light-hover": "#FFFDDF",
                    "light-active": "#FFFCBD",
                    DEFAULT: "#FFF429",
                    hover: "#E6DC25",
                    active: "#CCC321",
                    dark: "#BFB71F",
                    "dark-hover": "#999219",
                    "dark-active": "#736E12",
                    darker: "#59550E",
                },
                danger: {
                    light: "#FDE9E9",
                    "light-hover": "#FBDFDF",
                    "light-active": "#F8BCBC",
                    DEFAULT: "#E72727",
                    hover: "#D02323",
                    active: "#B91F1F",
                    dark: "#AD1D1D",
                    "dark-hover": "#8B1717",
                    "dark-active": "#681212",
                    darker: "#510E0E",
                },
                neutral: {
                    50: "#fafafa",
                    100: "#f5f5f5",
                    200: "#e5e5e5",
                    300: "#d4d4d4",
                    400: "#a3a3a3",
                    500: "#737373",
                    600: "#525252",
                    700: "#404040",
                    800: "#262626",
                    900: "#171717",
                    950: "#0a0a0a",
                },
            },
        },
    },

    plugins: [],
};
